### ISSUE TITLE
Include `lib` 

### ISSUE THREAD

**Issue by Padraic-O-Mhuiris** [nix-community/nix-unit#14]
Just discovered this and looks like a really promising tool. One suggestion would be to include a `lib` which could make test construction easier and enforce attrset shape using function arguments.

```nix
{
  testX = nix-unit.lib.testPass { expr = 1; expected = 1; };
  testY = nix-unit.lib.testFail { expr = 1; expected = "1"; };
  testZ = nix-unit.lib.testEvalAbort { expr = ..., msg = "..." };
}
```

I'm not sure if the `testEvalAbort` example would work as it might just abort the test if expr arg is evaluated incorrectly

**Comment by Padraic-O-Mhuiris** [comment]
Have been playing around with this a bit more and as far as I understand it evaluates each `test*` attrset independently (as separate processes?). One issue with adding extensibility above the basic test attrsets would be that test bootstrapping could become unwieldy. Some check evaluation might need to be ran prior to running the tests such that the bootstrapping process evaluates to the test attrset correctly. 
Maybe this can be done in nix itself but the logic would follow to eval each branch of whatever injested until an attrset containing `test*` is met, then the tests can be ran. Errors in the eval could be floated to the user in cases where this is not true.

**Comment by adisbladis** [comment]
I'd rather not do this as I think it obfuscates the readability & understandability of tests.
I think it's far better to have plain old attrsets.

>  it evaluates each test* attrset independently (as separate processes?)

Separately but in the same process. They are evaluated in sequence.
