### ISSUE TITLE
Core dumped

### ISSUE THREAD

**Issue by jkarni** [nix-community/nix-unit#169]
Thanks for this tool! It's quite nice!

One issue I encountered is that when I try running nix-unit in a devshell, outside of a derivation, I get a core dump:
```bash
nix-unit --flake .#tests                                             
warning: unknown setting 'allowed-users'
warning: unknown setting 'trusted-users'
warning: `--gc-roots-dir' not specified
/nix/store/6G5FHXV0BDM7236IXDWQ1IZZAWBC7GRM-gcc-13.2.0/include/c++/13.2.0/optional:477: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = std::__cxx11::basic_string<char>; _Dp = std::_Optional_base<std::__cxx11::basic_string<char>, false, false>]: Assertion 'this->_M_is_engaged()' failed.
[1]    13084 abort (core dumped)  nix-unit --flake .#tests
```
 
Inside of a derivation it works fine. 

For reference, the reproduction repo is [this](https://github.com/garnix-io/incrementalize). I'm on Nix 2.18.8 locally, on x86_64-linux.

If you have any pointers, happy to try fixing this myself!

**Comment by adisbladis** [comment]
Fixed in tag https://github.com/nix-community/nix-unit/releases/tag/v2.18.8
Nixpkgs 24.05 PR: https://github.com/NixOS/nixpkgs/pull/354611
